//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01", IsNullable=false)]
public partial class insuredPerson {
    
    private insuredPersonFullName fullNameField;
    
    private System.DateTime birthDateField;
    
    private string genderField;
    
    private byte snilsField;
    
    private byte innField;
    
    private insuredPersonIdentityDocument identityDocumentField;
    
    private insuredPersonRegAddress regAddressField;
    
    private insuredPersonMethodReceivePayment methodReceivePaymentField;
    
    /// <remarks/>
    public insuredPersonFullName fullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime birthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public byte snils {
        get {
            return this.snilsField;
        }
        set {
            this.snilsField = value;
        }
    }
    
    /// <remarks/>
    public byte inn {
        get {
            return this.innField;
        }
        set {
            this.innField = value;
        }
    }
    
    /// <remarks/>
    public insuredPersonIdentityDocument identityDocument {
        get {
            return this.identityDocumentField;
        }
        set {
            this.identityDocumentField = value;
        }
    }
    
    /// <remarks/>
    public insuredPersonRegAddress regAddress {
        get {
            return this.regAddressField;
        }
        set {
            this.regAddressField = value;
        }
    }
    
    /// <remarks/>
    public insuredPersonMethodReceivePayment methodReceivePayment {
        get {
            return this.methodReceivePaymentField;
        }
        set {
            this.methodReceivePaymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
public partial class insuredPersonFullName {
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string middleNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fss.ru/integration/types/person/v02")]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fss.ru/integration/types/person/v02")]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fss.ru/integration/types/person/v02")]
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
public partial class insuredPersonIdentityDocument {
    
    private insuredPersonIdentityDocumentPassport passportField;
    
    /// <remarks/>
    public insuredPersonIdentityDocumentPassport passport {
        get {
            return this.passportField;
        }
        set {
            this.passportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
public partial class insuredPersonIdentityDocumentPassport {
    
    private byte seriesField;
    
    private byte numberField;
    
    private System.DateTime issueDateField;
    
    private string whoIssuedField;
    
    /// <remarks/>
    public byte series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <remarks/>
    public byte number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime issueDate {
        get {
            return this.issueDateField;
        }
        set {
            this.issueDateField = value;
        }
    }
    
    /// <remarks/>
    public string whoIssued {
        get {
            return this.whoIssuedField;
        }
        set {
            this.whoIssuedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
public partial class insuredPersonRegAddress {
    
    private insuredPersonRegAddressFiasAddress fiasAddressField;
    
    private uint postalCodeField;
    
    /// <remarks/>
    public insuredPersonRegAddressFiasAddress fiasAddress {
        get {
            return this.fiasAddressField;
        }
        set {
            this.fiasAddressField = value;
        }
    }
    
    /// <remarks/>
    public uint postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
public partial class insuredPersonRegAddressFiasAddress {
    
    private string houseGuidField;
    
    private byte flatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fss.ru/integration/types/common/v01")]
    public string houseGuid {
        get {
            return this.houseGuidField;
        }
        set {
            this.houseGuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fss.ru/integration/types/common/v01")]
    public byte flat {
        get {
            return this.flatField;
        }
        set {
            this.flatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ru:fss:integration:types:rpu:InsuredPerson:v01")]
public partial class insuredPersonMethodReceivePayment {
    
    private bankInfo bankInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.fss.ru/integration/types/common/v01")]
    public bankInfo bankInfo {
        get {
            return this.bankInfoField;
        }
        set {
            this.bankInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fss.ru/integration/types/common/v01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.fss.ru/integration/types/common/v01", IsNullable=false)]
public partial class bankInfo {
    
    private string bankNameField;
    
    private uint bikField;
    
    private byte accountNumField;
    
    /// <remarks/>
    public string bankName {
        get {
            return this.bankNameField;
        }
        set {
            this.bankNameField = value;
        }
    }
    
    /// <remarks/>
    public uint bik {
        get {
            return this.bikField;
        }
        set {
            this.bikField = value;
        }
    }
    
    /// <remarks/>
    public byte accountNum {
        get {
            return this.accountNumField;
        }
        set {
            this.accountNumField = value;
        }
    }
}
